/**
 * Structured intent definitions and patterns catalogue.
 */

import { IntentDefinition } from "./types";

export const INTENT_DEFINITIONS: IntentDefinition[] = [
  {
    name: "EMERGENCY",
    description: "Urgent medical emergencies requiring immediate clinical intervention",
    priority: 100,
    patterns: [
      /\b(severe\s+chest\s+pain|chest\s+pain|heart\s+attack)\b/i,
      /\b(trouble\s+breathing|cannot\s+breathe|difficulty\s+breathing|shortness\s+of\s+breath)\b/i,
      /\b(unconscious|unresponsive|passed\s+out|collapsed|fainted)\b/i,
      /\b(severe\s+bleeding|heavy\s+bleeding|profuse\s+bleeding)\b/i,
      /\b(emergency\s+help|urgent\s+emergency|medical\s+emergency)\b/i,
      /\b(stroke|paralysis|sudden\s+numbness|face\s+drooping)\b/i,
      /\b(severe\s+sudden\s+symptoms|severe\s+pain)\b/i,
    ],
    keywords: [
      "chest pain",
      "heart attack",
      "breathing",
      "unconscious",
      "severe bleeding",
      "emergency",
      "stroke",
      "collapsed",
      "ambulance",
    ],
  },
  {
    name: "MEDICAL_ADVICE",
    description: "Requests for medical diagnosis, drug prescription, or clinical assessment",
    priority: 90,
    patterns: [
      /\b(what\s+medicine\s+should\s+i\s+take|which\s+medicine\s+is\s+best|what\s+tablet\s+should\s+i\s+take)\b/i,
      /\b(what\s+treatment\s+should\s+i\s+take|how\s+to\s+cure|how\s+to\s+treat)\b/i,
      /\b(do\s+i\s+have\s+diabetes|what\s+disease\s+do\s+i\s+have|diagnose\s+me|what\s+is\s+wrong\s+with\s+me)\b/i,
      /\b(what\s+does\s+my\s+report\s+mean|is\s+my\s+blood\s+sugar\s+dangerous|is\s+my\s+.*?\s+dangerou?s)\b/i,
      /\b(wbc\s+is\s+high|platelets\s+are\s+low|haemoglobin\s+is\s+low|high\s+creatinine|abnormal\s+report)\b/i,
      /\b(prescribe\s+(?:me|medicine)|suggest\s+medicine|recommend\s+tablet|medicine\s+for\s+fever)\b/i,
      /\b(interpret\s+(?:my\s+)?report|explain\s+my\s+results?)\b/i,
    ],
    keywords: [
      "medicine",
      "treatment",
      "tablet",
      "pill",
      "diagnose",
      "diagnosis",
      "disease",
      "cure",
      "prescribe",
      "symptom",
      "fever",
      "dangerous",
      "high wbc",
      "low wbc",
      "interpret report",
    ],
  },
  {
    name: "BOOK_TEST",
    description: "Starting or performing test enquiry / booking workflow",
    priority: 85,
    patterns: [
      /\b(i\s+want\s+to\s+book|book\s+(?:a\s+)?test|need\s+an?\s+appointment|schedule\s+(?:a\s+)?test)\b/i,
      /\b(i\s+want\s+to\s+get\s+.*?\s+done|i\s+want\s+to\s+book\s+.*?|can\s+i\s+schedule|how\s+can\s+i\s+book)\b/i,
      /\b(schedule\s+my\s+test|make\s+an?\s+appointment|reserve\s+a\s+test|book\s+appointment)\b/i,
      /\b(book\s+cbc|book\s+blood\s+test|book\s+sugar\s+test|book\s+thyroid|book\s+lipid)\b/i,
      /\b(take\s+appointment|test\s+booking|appointment\s+for\s+test)\b/i,
    ],
    keywords: [
      "book",
      "booking",
      "appointment",
      "schedule",
      "reserve",
      "slot",
    ],
    negationTriggers: [
      "do not want to book",
      "not want to book",
      "dont want to book",
      "no appointment",
      "do not need appointment",
    ],
  },
  {
    name: "CENTRE_INFO",
    description: "General information about Asha Jyothi Diagnostic Centre background",
    priority: 82,
    patterns: [
      /\b(tell\s+me\s+about\s+the\s+centre|what\s+is\s+this\s+diagnostic\s+centre|what\s+do\s+you\s+do)\b/i,
      /\b(tell\s+me\s+about\s+asha\s+jyothi|about\s+the\s+centre|about\s+asha\s+jyothi|who\s+are\s+you)\b/i,
      /\b(what\s+is\s+asha\s+jyothi|centre\s+details|about\s+lab|about\s+diagnostic\s+centre)\b/i,
    ],
    keywords: [
      "about the centre",
      "about asha jyothi",
      "tell me about the centre",
      "who are you",
      "what is asha jyothi",
      "about centre",
    ],
  },
  {
    name: "TEST_PREPARATION",
    description: "Fasting and pre-test preparation instructions",
    priority: 80,
    patterns: [
      /\b(do\s+i\s+need\s+to\s+fast|should\s+i\s+fast|how\s+should\s+i\s+prepare|how\s+to\s+prepare)\b/i,
      /\b(can\s+i\s+eat\s+before|what\s+should\s+i\s+do\s+before|can\s+i\s+drink\s+water\s+before)\b/i,
      /\b(fasting\s+required|need\s+fasting|fasting\s+for|empty\s+stomach|fasting\s+hours)\b/i,
      /\b(preparation\s+for\s+.*?\s+test|preparation\s+needed|diet\s+before\s+test)\b/i,
    ],
    keywords: [
      "fast",
      "fasting",
      "eat",
      "food",
      "empty stomach",
      "water before",
      "preparation",
      "prepare",
      "overnight fasting",
    ],
  },
  {
    name: "TEST_PRICE",
    description: "Pricing and cost enquiries for tests",
    priority: 75,
    patterns: [
      /\b(how\s+much\s+(?:does|is|for)|what\s+is\s+the\s+price|how\s+much\s+do\s+you\s+charge)\b/i,
      /\b(cost\s+of|test\s+cost|price\s+of|price\s+list|test\s+price|rate\s+of|charges?\s+for)\b/i,
      /\b(what\s+are\s+your\s+rates|fees?\s+for|fee\s+structure)\b/i,
    ],
    keywords: [
      "price",
      "cost",
      "charge",
      "charges",
      "rate",
      "rates",
      "fee",
      "fees",
      "how much",
      "expensive",
      "rupees",
    ],
  },
  {
    name: "TEST_AVAILABILITY",
    description: "Inquiries about tests offered and available diagnostic catalogue",
    priority: 70,
    patterns: [
      /\b(what\s+tests\s+do\s+you\s+offer|which\s+tests\s+are\s+available|what\s+blood\s+tests\s+do\s+you\s+have)\b/i,
      /\b(do\s+you\s+do\s+.*?|is\s+.*?\s+available|can\s+i\s+get\s+a\s+.*?\s+test|do\s+you\s+have\s+.*?)\b/i,
      /\b(what\s+diagnostic\s+tests\s+can\s+i\s+do|which\s+tests\s+can\s+i\s+get|tests?\s+list|list\s+of\s+tests?)\b/i,
      /\b(available\s+tests?|all\s+tests?|show\s+tests?|blood\s+test\s+options)\b/i,
    ],
    keywords: [
      "tests available",
      "what tests",
      "which tests",
      "test list",
      "available tests",
      "offer",
      "do you have",
      "do you do",
    ],
  },
  {
    name: "TEST_INFORMATION",
    description: "Detailed medical context and information about a specific test",
    priority: 65,
    patterns: [
      /\b(what\s+is\s+(?:cbc|hba1c|lipid|thyroid|vitamin\s*d|lft|kft|glucose|hemogram|blood\s*sugar))\b/i,
      /\b(tell\s+me\s+about\s+(?:cbc|hba1c|lipid|thyroid|vitamin\s*d|lft|kft|glucose|hemogram|blood\s*sugar))\b/i,
      /\b(what\s+does\s+.*?\s+(?:test\s+)?(?:check|measure|show))\b/i,
      /\b(why\s+is\s+.*?\s+tested|why\s+is\s+.*?\s+done|explain\s+(?:cbc|hba1c|lipid|thyroid|vitamin\s*d|lft|kft))\b/i,
      /\b(details\s+of\s+(?:cbc|hba1c|lipid|thyroid|vitamin\s*d|lft|kft)|what\s+is\s+a\s+.*?\s+test)\b/i,
    ],
    keywords: [
      "what does test check",
      "why is test done",
      "test check",
      "test measure",
    ],
  },
  {
    name: "HOME_SAMPLE_COLLECTION",
    description: "Inquiries about doorstep / home sample collection",
    priority: 60,
    patterns: [
      /\b(do\s+you\s+collect\s+samples?\s+at\s+home|can\s+someone\s+come\s+to\s+my\s+house)\b/i,
      /\b(home\s+(?:blood|sample)?\s*collection|can\s+i\s+give\s+blood\s+sample\s+from\s+home)\b/i,
      /\b(do\s+you\s+provide\s+home\s+collection|can\s+you\s+collect\s+my\s+sample\s+at\s+home)\b/i,
      /\b(doorstep\s+collection|home\s+visit|phlebotomist\s+visit|sample\s+pickup)\b/i,
    ],
    keywords: [
      "home collection",
      "sample at home",
      "doorstep",
      "come to my house",
      "home sample",
      "home blood",
      "visit home",
    ],
  },
  {
    name: "REPORT_INFORMATION",
    description: "Turnaround time, collection methods, and format of test reports",
    priority: 55,
    patterns: [
      /\b(when\s+will\s+i\s+get\s+my\s+report|how\s+do\s+i\s+collect\s+my\s+report|can\s+i\s+get\s+my\s+report\s+online)\b/i,
      /\b(how\s+long\s+do\s+reports\s+take|where\s+can\s+i\s+get\s+my\s+report|is\s+my\s+report\s+ready)\b/i,
      /\b(report\s+delivery|report\s+status|report\s+time|download\s+report|online\s+reports?)\b/i,
    ],
    keywords: [
      "report",
      "reports",
      "turnaround",
      "online report",
      "report ready",
      "collect report",
      "report timing",
    ],
  },
  {
    name: "LOCATION",
    description: "Physical location, address, landmarks, and map guidance",
    priority: 50,
    patterns: [
      /\b(where\s+are\s+you\s+located|where\s+is\s+the\s+centre|what\s+is\s+your\s+address)\b/i,
      /\b(location\s+please|how\s+do\s+i\s+reach\s+you|where\s+is\s+asha\s+jyothi)\b/i,
      /\b(are\s+you\s+in\s+toopran|directions|map\s+link|google\s+maps|address\s+of\s+lab)\b/i,
    ],
    keywords: [
      "location",
      "located",
      "address",
      "where",
      "toopran",
      "directions",
      "maps",
      "reach",
      "place",
    ],
  },
  {
    name: "TIMINGS",
    description: "Operating hours, opening, closing times, and Sunday schedule",
    priority: 45,
    patterns: [
      /\b(what\s+are\s+your\s+timings|when\s+are\s+you\s+open|when\s+does\s+the\s+lab\s+open)\b/i,
      /\b(when\s+do\s+you\s+close|are\s+you\s+open\s+today|what\s+time\s+can\s+i\s+visit)\b/i,
      /\b(operating\s+hours|working\s+hours|sunday\s+timings?|opening\s+time|closing\s+time)\b/i,
    ],
    keywords: [
      "timings",
      "timing",
      "hours",
      "hour",
      "open",
      "close",
      "opening",
      "closing",
      "sunday",
      "schedule",
    ],
  },
  {
    name: "CONTACT",
    description: "Phone numbers, email, WhatsApp, and contact channels",
    priority: 40,
    patterns: [
      /\b(phone\s+number|contact\s+number|how\s+can\s+i\s+contact\s+you|give\s+me\s+your\s+number)\b/i,
      /\b(how\s+do\s+i\s+call\s+the\s+centre|do\s+you\s+have\s+whatsapp|email\s+address)\b/i,
      /\b(customer\s+care|front\s+desk\s+number|call\s+you|contact\s+details)\b/i,
    ],
    keywords: [
      "contact",
      "phone",
      "number",
      "call",
      "whatsapp",
      "email",
      "mobile",
      "telephone",
    ],
  },
  {
    name: "SERVICES",
    description: "Broad categories of diagnostic and clinical services offered",
    priority: 35,
    patterns: [
      /\b(what\s+services\s+do\s+you\s+provide|what\s+do\s+you\s+offer|what\s+can\s+i\s+get\s+done\s+here)\b/i,
      /\b(what\s+diagnostic\s+services\s+are\s+available|do\s+you\s+provide\s+blood\s+tests|do\s+you\s+provide\s+pathology)\b/i,
      /\b(list\s+of\s+services|our\s+services|all\s+services|health\s+services)\b/i,
    ],
    keywords: [
      "services",
      "service",
      "facilities",
      "facility",
      "departments",
      "offerings",
      "pathology services",
    ],
  },
  {
    name: "GREETING",
    description: "Polite opening greetings and welcome messages",
    priority: 25,
    patterns: [
      /^(hi|hello|hey|namaste|hi\s+there|good\s+morning|good\s+afternoon|good\s+evening|greetings)[\s!.]*$/i,
      /\b(hello\s+there|hey\s+there|namaskaram)\b/i,
    ],
    keywords: [
      "hi",
      "hello",
      "hey",
      "namaste",
      "good morning",
      "good afternoon",
      "good evening",
      "hi there",
    ],
  },
  {
    name: "THANK_YOU",
    description: "Expressions of gratitude",
    priority: 20,
    patterns: [
      /^(thanks|thank\s+you|thank\s+u|appreciate\s+it|many\s+thanks|thanks\s+a\s+lot)[\s!.]*$/i,
      /\b(thank\s+you\s+so\s+much|thanks\s+for\s+the\s+help|great\s+thanks)\b/i,
    ],
    keywords: [
      "thanks",
      "thank you",
      "thank u",
      "appreciate it",
      "many thanks",
    ],
  },
  {
    name: "GOODBYE",
    description: "Polite closings and conversation endings",
    priority: 15,
    patterns: [
      /^(bye|goodbye|see\s+you|that\s*is\s*all|thats\s+all|talk\s+later|have\s+a\s+good\s+day)[\s!.]*$/i,
      /\b(bye\s+bye|take\s+care|catch\s+you\s+later)\b/i,
    ],
    keywords: [
      "bye",
      "goodbye",
      "see you",
      "that's all",
      "thats all",
      "talk later",
      "bye bye",
    ],
  },
  {
    name: "HELP",
    description: "Assistance on what the chatbot can do and sample questions",
    priority: 10,
    patterns: [
      /^(help|what\s+can\s+you\s+do|what\s+can\s+i\s+ask|how\s+can\s+you\s+help\s+me|menu|options)[\s!.]*$/i,
      /\b(how\s+to\s+use|guide\s+me|assist\s+me|chatbot\s+capabilities)\b/i,
    ],
    keywords: [
      "help",
      "what can you do",
      "what can i ask",
      "how can you help",
      "menu",
      "capabilities",
    ],
  },
  {
    name: "UNKNOWN",
    description: "Fallback for unrecognized or low-confidence queries",
    priority: 0,
    patterns: [],
    keywords: [],
  },
];
